title: Think Design
baseURL: /
params:
  accent_color: violet
  color_scheme: light
  footer:
    content: '&copy; Think Design. All rights reserved.'
    has_social: true
    links:
      - new_window: false
        text: think design
        url: 'https://www.thinkdesign.com'
  header:
    has_nav: true
    title: Think Design
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
